[project]
name = "kubernetes-resource"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "loguru>=0.7.3",
    "typer>=0.12.0",
    "tqdm>=4.66.0",
]
